services:  
  database:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:    
      MYSQL_ROOT_PASSWORD: 124
      MYSQL_DATABASE: prueba
      MYSQL_USER: fabiola
      MYSQL_PASSWORD: 12345

  flask:  
    build: ./app
    ports:
      - 5000:5000
    depends_on:
     - database

